# Generated by Django 5.0.1 on 2024-02-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('novel_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Novels',
            fields=[
                ('novel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author_id', models.IntegerField()),
                ('publish_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
