# Generated by Django 5.0.1 on 2024-02-21 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0003_alter_chapters_novel_id_alter_novels_author_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapters',
            new_name='Chapter',
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('novel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('r', '连载中'), ('f', '已完成')], max_length=1)),
                ('enable', models.BooleanField(default=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.AlterField(
            model_name='chapter',
            name='novel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workedit.novel'),
        ),
        migrations.DeleteModel(
            name='Novels',
        ),
    ]
