# Generated by Django 5.0.1 on 2024-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0004_rename_chapters_chapter_novel_alter_chapter_novel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='novel_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
