# Generated by Django 5.0.1 on 2024-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0005_alter_novel_novel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='renew_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='introduction',
            field=models.CharField(default='我们的征途是诸天万界！', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('r', '连载中'), ('f', '已完成')], default='r', max_length=1),
        ),
    ]
