# Generated by Django 5.0.1 on 2024-02-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0006_chapter_enable_chapter_renew_time_novel_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='introduction',
            field=models.CharField(default='我们的征途是诸天万界！', max_length=200, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='作品名 '),
        ),
    ]
