# Generated by Django 5.0.1 on 2024-02-22 14:03

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0007_alter_chapter_chapter_id_alter_novel_introduction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_id']},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=100, verbose_name='章节名'),
        ),
    ]
