# Generated by Django 5.0.1 on 2024-03-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0010_rename_user_id_aiapikey_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiapikey',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='aiapikey',
            unique_together={('key', 'key_name')},
        ),
    ]
