# Generated by Django 5.0.1 on 2024-03-01 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0011_aiapikey_enable_alter_aiapikey_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIapi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=20, unique=True)),
                ('api_url', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.AlterField(
            model_name='aiapikey',
            name='key_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workedit.aiapi', to_field='api_name', verbose_name='api名称'),
        ),
    ]
