# Generated by Django 5.0.1 on 2024-03-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0012_aiapi_alter_aiapikey_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiapi',
            name='renew_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
