# Generated by Django 5.0.1 on 2024-03-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0013_aiapi_renew_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiapi',
            name='renew_time',
        ),
    ]
