# Generated by Django 5.0.1 on 2024-03-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0014_remove_aiapi_renew_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='publish_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='novel',
            name='publish_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='novel',
            name='renew_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次更新时间'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='renew_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次更新时间'),
        ),
    ]
