# Generated by Django 5.0.1 on 2024-03-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0017_uploadnovel_check_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadnovel',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
