# Generated by Django 5.0.1 on 2024-03-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workedit', '0018_alter_uploadnovel_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='base_novel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='novel',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
