# Generated by Django 5.0.1 on 2024-08-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="back_content",
            field=models.TextField(),
        ),
    ]
