# Generated by Django 5.0.1 on 2024-08-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard", "0002_alter_flashcard_back_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="flashcardset",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="flashcardset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
