# Generated by Django 5.0.1 on 2024-03-11 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='txttoaduiodata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='text')),
                ('voicer', models.IntegerField(choices=[(1, '度小宇'), (0, '度小美'), (3, '度逍遥（基础）'), (4, '度丫丫'), (5003, '度逍遥（精品）'), (5118, '度小鹿'), (106, '度博文'), (110, '度小童'), (111, '度小萌'), (103, '度米朵'), (5, '度小娇')], default=0, verbose_name='配音员')),
                ('speed', models.IntegerField(default=5, verbose_name='语速')),
                ('pitch', models.IntegerField(default=5, verbose_name='音调')),
                ('volume', models.IntegerField(default=5, verbose_name='音量')),
                ('audio_format', models.IntegerField(choices=[(3, 'mp3'), (4, 'pcm-16k'), (5, 'pcm-8k'), (6, 'wav')], default=3, verbose_name='音频格式')),
                ('audio_url', models.TextField(null=True, verbose_name='音频URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文本转语音数据',
                'verbose_name_plural': '文本转语音数据',
                'ordering': ['-created_at'],
            },
        ),
    ]
